version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # specify the Node.js version
    commands:
      - npm install -g aws-cdk # install the AWS CDK toolkit globally
      - npm install # install project dependencies

  build:
    commands:
      - echo $env
      - npm test
      - cdk synth # synthesize the CDK app

  post_build:
    commands:
      - cdk deploy --require-approval never # deploy the CDK app

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out # output directory for synthesized CloudFormation templates
